general {
    # 核心：触发锁屏的具体命令
    lock_cmd = quickshell ipc call lock open  
    
    # 系统休眠或睡眠前，向 systemd 发送锁屏信号，这会触发上面的 lock_cmd
    before_sleep_cmd = loginctl lock-session    
    
    # 系统唤醒后，确保屏幕被点亮，避免需要按两次键才亮屏
    after_sleep_cmd = niri msg action power-on-monitors  
}

# listener {
#     timeout = 150                                # 2.5分钟无操作
#     on-timeout = brightnessctl -s set 10         # 降低屏幕亮度到10%
#     on-resume = brightnessctl -r                 # 恢复屏幕亮度
# }
#
# # 如果你的笔记本键盘没有背光，可以把这段注释掉
# listener { 
#     timeout = 150                                          # 2.5分钟无操作
#     on-timeout = brightnessctl -sd rgb:kbd_backlight set 0 # 关闭键盘背光
#     on-resume = brightnessctl -rd rgb:kbd_backlight        # 恢复键盘背光
# }

listener {
    timeout = 300                                 # 5分钟无操作
    on-timeout = loginctl lock-session            # 发送锁屏信号（触发 quickshell 锁屏）
}

# listener {
#     timeout = 330                                 # 5.5分钟无操作
#     # 核心：使用 Niri 的指令关闭屏幕
#     on-timeout = niri msg action power-off-monitors  
#
#     # 核心：活动恢复时，使用 Niri 的指令点亮屏幕，并恢复亮度
#     on-resume = niri msg action power-on-monitors && brightnessctl -r  
# }

listener {
    timeout = 1800                                # 30分钟无操作
    on-timeout = systemctl suspend                # 让系统进入睡眠（挂起到内存）
}
